language: android
android:
  components:
    - android-28
    - build-tools-28.0.3

env:
  global:
   # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8

# Run assemble and unit tests
script:
  - ./gradlew clean assembleDebug
  
deploy:
  provider: assembleDebug
  api_key: $GIT_KEY
  file_glob: true
  file: $TRAVIS_BUILD_DIR/app/build/outputs/apk/debug/*.apk
  skip_cleanup: true
  overwrite: true
  prerelease: true
  target_commitsh: $TRAVIS_COMMIT
  on:
    branch: master
    repo: JayeshVarotariya/KotlineDemo
    
after_deploy:
  - rm -rf $TRAVIS_BUILD_DIR/app/build/outputs
